controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

redirect:
    path: /{hash}
    controller: App\Controller\RedirectLinkController::redirectLink

home:
    path: /
    controller: App\Controller\HomePageController::index
